language: java
jdk:
- oraclejdk8
script: ./gradlew build gitPublishPush  --stacktrace
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
env:
  global:
    secure: "kpM52XSa/Z4m19+9LHQpuP4DFFOjn6ItVpBj0mClGUcyxCtYY6/NKlffl0HtMpcIjzCzelADA1Zo02dLM4jLqOpYvyTMQjcRAYHjDOUbSRdqha1SNvWS0vx780vKUH8jx3tZ9maY+hV2cWYiYhfJTnj8/YDSmNoM4jaUs1HGCdIaOp9iPlMjPEAu7fCPITNsX1TRUZOc/z8lNf3mkEQUDDedwH9QkFoqOlBgdvlQU9T6nI5fKMQcIJtUrOwfBA1C9+9g4CnQtK5/I7j2l9yLbtCr2P473AJ/10HBSaVGi9OZoYtyTjay1+QGxeTc1A9h0r0GsQyEcKpb7PF9V6PIa1PRar1TAbU1sRL4iO9G+ZmDS63hy5eHBX1+GJoUCRjpav3kssn9tElz8fuGfbz7vRdmhYc7TyDLUmZKCTXTme+23DvVQ1PLAHqi+wai5fuB49c/gDpcoP63Pp0yhRYWWkUeDHQwrh0fGyqY2hXJx+bKUffK0jzQwe3VDe7Xd3RtCd43NEfjCqC3tO0QjcM/bL8Ex4BDhbH1/7sbn13SQFXasJSqtMUjohRB9y8oXrAjP4A3X/vyH4mxxiFTivdhr1yzFLQT+wbwcVmaAAOiWahDUCgjx/d7Ybp/+tSVSlJGtOdUaHI7qvxSoa4WhafjGYGcojC8RlQM5ScH7SN4xmc="
notifications:
  slack:
    on_success: change
    rooms:
      secure: 1pJzgkUfiSP/KX5TuAsAgKhFtaVcfVWwdK+rbHMpzX0herxB4aAtVh3V1EnkiOgPkCcehviLC5MsEDxgwMsLt7Ko7RQsZLd42w8dxv+cxQad4f3LPlej6G2QJMjO0+JeDDC++lBcYsj932buT7XqZQ37QYGuM2GOp3bOqwhZ0mpHgyQ/pWw+m0upiJL1Z/snjt6tLsQejUKFkl71omDleB/JPmgSDgXWIBBtPkR+J4ScH9cSXWgtuks30kk/BcI6NOGNDkieJb32K8xDxE8VlK7OY2TNGAEzHD4tFBHQMDLeWQvkc7tPWq9D4GZ2YyJpeq+wnKqu2xZOTkqq6hCDAHhaEGj8CPztHCsg1BdSc6Sq7yJxA8JDvWzh8v8nqRkhiIRPwAjX83DEJYvsA32ytQmibfBq2TEQMhiIDPp5H4YixdGqLxPCXFqR5H+JOwARllYCoMTbSxJimnfLdCFyFhXiX3LTne8GPJnoJx7nsizLSdJ4Ww8XdYmMAHP2QDBQFTdsJpHorm1/FCdqBXdcXNiY6vqRnGHzmiun+3cQEmHfwsiZ3pd4DFgaNjnjxc0zoW+0Qci7ybVtxG5xdFOg8jA/NvnDiEzdg20evNJk1WDboEuHg6eFjVJsjYhElQAcmZEgMjn24Ve/jAqxwcrcGIh5F6p3vmQWeBlgAdptbWU=
